
name: Terraform Deployment - Account3

on:
  push:
    paths:
      - 'accounts/account3/**'
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply - Account3'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: accounts/account3

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCOUNT3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCOUNT3_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_ACCOUNT3_REGION }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init -backend-config="backend.s3.tfbackend"

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
